class CfgLoot {
        trash[] = {
                {
                        "TrashTinCan",
                        "TrashJackDaniels",
						"FoodCanBakedBeans",
                        "FoodCanSardines",
                        "FoodCanFrankBeans",
						"ItemSodaCoke",
                        "ItemSodaPepsi",
                        "FoodCanBakedBeans",
						"15Rnd_W1866_Pellet",
                        "FoodCanSardines",
                        "FoodCanFrankBeans",
                        "FoodCanPasta",
                        "16Rnd_9x21_Mag",
                        "8Rnd_B_Beneli_Pellets",
                        "16Rnd_9x21_Mag",
                        "30Rnd_45ACP_Mag_SMG_01",
                        "ItemBandage",
                        "FoodCanBakedBeans",
                        "equip_rag",
                        "30Rnd_9x21_Mag",
						"15Rnd_W1866_Pellet",
                        "ItemSodaEmpty"
                },
                {
                        0.01,
                        0.01,
						0.01,
						0.01,
						0.01,
						0.01,
						0.01,
						0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01
                }
        };
        civilian[] = {
                {
                        "TrashTinCan",
                        "TrashJackDaniels",
                        "ItemSodaEmpty",
                        "ItemSodaCoke",
                        "ItemSodaPepsi",
                        "FoodCanBakedBeans",
						"15Rnd_W1866_Pellet",
                        "FoodCanSardines",
                        "FoodCanFrankBeans",
                        "FoodCanPasta",
                        "15Rnd_W1866_Pellet",
                        "8Rnd_B_Beneli_Pellets",
                        "16Rnd_9x21_Mag",
                        "30Rnd_45ACP_Mag_SMG_01",
                        "ItemBandage",
                        "FoodCanBakedBeans",
                        "equip_rag",
                        "HandRoadFlare",
                        "30Rnd_9x21_Mag"
                },
                {
                        0.01,
                        0.01,
                        0.01,
                        0.01,
						0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01
                }
        };
        foodt[] = {
                {
                        "ItemSodaCoke",
                        "ItemSodaPepsi",
                        "ItemBandage",
                        "FoodCanSardines",
                        "FoodCanFrankBeans",
                        "FoodCanPasta",
                        "FoodCanUnlabeled",
                        "FoodPistachio",
                        "FoodNutmix",
						"FoodCanUnlabeled",
		                "FoodCanRusUnlabeled",
		                "FoodCanRusStew",
		                "FoodCanRusPork",
		                "FoodCanRusPeas",
		                "FoodCanRusMilk",
		                "FoodCanRusCorn",
		                "FoodPistachio",
		                "FoodNutmix",
						"ItemSodaCokeEmpty",
		                "ItemSodaPepsiEmpty",
		                "FoodCanUnlabeledEmpty",
		                "FoodCanRusUnlabeledEmpty",
		                "FoodCanRusPorkEmpty",
		                "FoodCanRusPeasEmpty",
		                "FoodCanRusMilkEmpty",
		                "FoodCanRusCornEmpty",
		                "FoodCanRusStewEmpty",
		                "TrashTinCan",
		                "TrashJackDaniels",
		                "ItemSodaEmpty",
		                "ItemTrashToiletpaper",
		                "ItemTrashRazor"
                },
                {
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
						0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
						0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
						0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05
                }
        };
        generic[] = {
                {
                        "TrashTinCan",
                        "ItemSodaEmpty",
                        "ItemSodaCoke",
                        "ItemSodaPepsi",
                        "TrashJackDaniels",
                        "FoodCanBakedBeans",
                        "FoodCanSardines",
                        "FoodCanFrankBeans",
                        "ItemEpinephrine",
                        "ItemWaterbottleUnfilled",
                        "ItemWaterbottle",
                        "FoodCakeCremeCakeClean",
                        "15Rnd_W1866_Pellet",
                        "8Rnd_B_Beneli_Pellets",
                        "16Rnd_9x21_Mag",
                        "ItemBandage",
                        "16Rnd_9x21_Mag",
                        "ItemAntibacterialWipe",
                        "30Rnd_45ACP_Mag_SMG_01",
                        "30Rnd_9x21_Mag",
                        "FlareGreen_F",
                        "ItemBandage",
                        "Chemlight_blue",
                        "DN_30Rnd_556x45_B_Stanag",
                        "Chemlight_red",
                        "Chemlight_green",
                        "ItemHeatPack",
                        "15Rnd_W1866_Pellet",
                        "8Rnd_B_Beneli_Pellets",
                        "30Rnd_45ACP_Mag_SMG_01",
                        "FlareGreen_F",
						"equip_nails",
	                    "equip_gauze",
	                    "equip_string",
	                    "equip_rag",
	                    "equip_scrapelectronics",
	                    "equip_floppywire",
	                    "equip_hose",
	                    "equip_duct_tape"
                },
                {
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
						0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05,
                        0.05
                }
        };
        medical[] = {
                {
                        "ItemBandage",
                        "ItemPainkiller",
                        "ItemMorphine",
                        "ItemEpinephrine",
                        "ItemAntibiotic",
                        "ItemHeatPack",
                        "HandRoadFlare"
                },
                {
                        0.8,
                        0.5,
                        0.5,
                        0.2,
                        0.3,
                        0.1,
                        0.2
                }
        };
        hospital[] = {
                {
                        "ItemBandage",
                        "ItemPainkiller",
                        "ItemMorphine",
                        "ItemEpinephrine",
                        "ItemBloodbag",
                        "ItemAntibiotic",
                        "HandRoadFlare"
                },
                {
                        0.33,
                        0.17,
                        0.13,
                        0.09,
                        0.17,
                        0.12,
                        0.05
                }
        };
        military[] = {
                {
                        "TrashTinCan",
                        "ItemSodaEmpty",
                        "ItemSodaCoke",
                        "ItemSodaPepsi",
                        "ItemBandage",
                        "ItemAntibiotic",
                        "ItemMorphine",
						"8Rnd_B_Beneli_Pellets",
                        "30Rnd_556x45_Stanag", //"30Rnd_556x45_Stanag"-Q
                        "DN_30Rnd_556x45_B_Stanag", //"20Rnd_762x51_DMR" -Q
                        "ItemBandage", //"17Rnd_9x19_glock17"-Q
                        "15Rnd_W1866_Pellet",
                        "16Rnd_9x21_Mag", //"15Rnd_9x19_M9"-Q
                        "30Rnd_65x39_caseless_green", //"30Rnd_762x39_AK47"-Q
                        "30Rnd_65x39_caseless_green", //"30Rnd_545x39_AK"-Q
                        "20Rnd_762x51_Mag", //"5Rnd_762x51_M24"-Q
                        "5Rnd_127x108_Mag", //"10Rnd_127x99_m107"-Q
                        "30Rnd_45ACP_Mag_SMG_01", //"8Rnd_B_Beneli_74Slug"-Q
                        "1Rnd_HE_Grenade_shell", //"1Rnd_HE_M203"-Q
                        "1Rnd_Smoke_Grenade_shell", //"FlareWhite_M203"-Q
                        "1Rnd_SmokeGreen_Grenade_shell", //"FlareGreen_M203"-Q
                        "1Rnd_SmokeRed_Grenade_shell", //"1Rnd_Smoke_M203"-Q            
                        "200Rnd_65x39_cased_Box", //"200Rnd_556x45_M249"-Q
                        "HandGrenade_Stone", //"HandGrenade_west"-Q
                        "SmokeShell",
                        "SmokeShellRed",
                        "SmokeShellGreen",
                        "30Rnd_9x21_Mag", //"8Rnd_B_Beneli_Pellets"-Q
                        "30Rnd_65x39_caseless_green", //"30Rnd_556x45_StanagSD"-Q
                        "30Rnd_65x39_caseless_mag", //"30Rnd_9x19_MP5"-Q
                        "30Rnd_556x45_Stanag", //"30Rnd_9x19_MP5SD"-Q
                        "200Rnd_65x39_cased_Box", //"100Rnd_762x51_M240"-Q
                        "Chemlight_blue",
                        "Chemlight_yellow",
                        "Chemlight_red",
                        "Chemlight_green",
                        "ItemHeatPack",
                        "FoodMRE",
                        "HandRoadFlare",
                        "15Rnd_W1866_Pellet",
                        "20Rnd_762x51_Mag", //"30Rnd_9x19_UZI_SD"-Q
                        "8Rnd_B_Beneli_Pellets",
                        "DN_30Rnd_556x45_B_Stanag", //"75Rnd_545x39_RPK"-Q
                        "16Rnd_9x21_Mag", //"9Rnd_45ACP_Mag"-Q
                        "16Rnd_9x21_Mag",
                        "30Rnd_65x39_caseless_mag",
                        "30Rnd_45ACP_Mag_SMG_01", //"kar98_mag",-Q
                        "SmokeShellBlue",                //"SmokeShellTear",-Q
                        "SmokeShellGreen",   //"SmokeShellBio",-Q
                        "30Rnd_45ACP_Mag_SMG_01", //"2Rnd_9x18_Tranq",-Q
                        "FlareGreen_F",
						"equip_nails",
	                    "equip_gauze",
	                    "equip_string",
	                    "equip_rag",
	                    "equip_scrapelectronics",
	                    "equip_floppywire",
	                    "equip_hose",
	                    "equip_duct_tape"
                },
                {
                        0.05,
                        0.01,
                        0.01,
                        0.04,
                        0.04,
                        0.04,
                        0.01,
                        0.04,
						0.04,
                        0.04,
                        0.05,
                        0.02,
                        0.02,
                        0.04,
                        0.04,
                        0.03,
                        0.01,
                        0.04,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.04,
                        0.02,
                        0.02,
                        0.04,
                        0.03,
                        0.02,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.04,
                        0.03,
                        0.05,
                        0.02,
                        0.01,
                        0.05,
                        0.01,
                        0.05,
                        0.01,
                        0.03,
                        0.05,
                        0.05,
                        0.02,
                        0.05,
                        0.01,
						0.05,
                        0.01,
                        0.03,
                        0.05,
                        0.05,
                        0.02,
                        0.05,
                        0.01
                }
        };
        policeman[] = {
                {
                        "ItemBandage",
                        "16Rnd_9x21_Mag", //"7Rnd_45ACP_1911"-Q
                        "16Rnd_9x21_Mag", //"6Rnd_45ACP"-Q
                        "30Rnd_45ACP_Mag_SMG_01", //"15Rnd_W1866_Slug"-Q
                        "30Rnd_9x21_Mag", 
                        "Chemlight_blue",
                        "Chemlight_yellow",
                        "Chemlight_red",
                        "Chemlight_green",
                        "HandRoadFlare",
                        "15Rnd_W1866_Pellet",
                        "8Rnd_B_Beneli_Pellets",
                        "30Rnd_45ACP_Mag_SMG_01", //"2Rnd_9x18_Tranq",-Q
                        "FlareGreen_F",
						"equip_nails",
	                    "equip_gauze",
	                    "equip_string",
	                    "equip_rag",
	                    "equip_scrapelectronics",
	                    "equip_floppywire",
	                    "equip_hose",
	                    "equip_duct_tape"
                },
                {
                        1,
                        0.8,
                        0.3,
                        0.3,
                        0.5,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.03,
                        0.02,
                        0.03,
                        0.01,
						0.01,
                        0.01,
                        0.01,
                        0.01,
                        0.03,
                        0.02,
                        0.03,
                        0.01
                }
        };
        hunter[] = {
                {
                        "ItemBandage",
                        "30Rnd_45ACP_Mag_SMG_01", //"5x_22_LR_17_HMR"-Q
                        "16Rnd_9x21_Mag", //"7Rnd_45ACP_1911"-Q
                        "15Rnd_W1866_Pellet",
						"8Rnd_B_Beneli_Pellets",
                        "ItemWaterbottleUnfilled",
                        "WoodenArrow",
                        "ItemHeatPack",
                        "FoodMRE",
                        "FoodNutmix",
                        "30Rnd_9x21_Mag", //"9Rnd_45ACP_Mag"-Q
                        "30Rnd_45ACP_Mag_SMG_01" //"kar98_mag",-Q
                },
                {
                        1,
                        0.5,
                        0.2,
                        0.5,
						0.5,
                        0.2,
                        1,
                        0.2,
                        0.04,
                        0.1,
                        0.02,
                        0.05
                }
        };
		casque[] = {
		{
"h_beret_blk_police","h_booniehat_dirty","h_cap_blk","h_cap_brn_specops","h_crewhelmetheli_b","h_helmetb_plain_blk","h_watchcap_sgg","H_Bandanna_surfer","H_Bandanna_khk","H_Shemag_khk","H_Beret_blk","H_Watchcap_khk","H_StrawHat"
		},
		{
			1,
			0.5,
			0.2,
			0.5,
			0.2,
			1,
			0.2
		}
	};
	chest[] = {
		{
        "v_bandollierb_khk","v_chestrig_khk","v_harnesso_brn","v_platecarrier1_cbr","v_platecarrieriagl_dgtl","v_rebreather_b","v_tacvest_blk_police","V_TacVest_camo","V_HarnessOGL_gry","V_PlateCarrierIA1_dgtl","V_PlateCarrierIA2_dgtl","V_RebreatherIA"
		},
		{
			1,
			0.5,
			0.2,
			0.5,
			0.2,
			0.2,
			0.2
		}
	};
	unifo[] = {
		{
		"u_b_ghilliesuit","u_c_poloshirt_tricolour","u_competitor","u_i_combatuniform_shortsleeve","U_IG_Guerilla1_1","u_i_officeruniform","U_B_Wetsuit","U_B_CombatUniform_mcam_tshirt","CombatUniform_cia","U_IG_Guerilla2_1","U_IG_Guerilla3_1","U_BG_Guerilla1_1","U_I_CombatUniform_tshirt"
		},
		{
			0.2,
			0.5,
			0.2,
			0.5,
			0.2,
			0.2,
			0.2,
			0.4,
			0.1
		}
	};
	accessprim[] = {
		{
		"acc_flashlight","muzzle_snds_B","muzzle_snds_H","muzzle_snds_L","optic_Aco","optic_Arco","optic_Hamr","optic_Holosight","acc_pointer_IR","optic_SOS","optic_MRCO"
		},
		{
			0.2,
			0.5,
			0.2,
			0.5,
			0.2,
			0.2,
			0.2,
			0.4,
			0.1,
			0.2,
			0.5
		}
	};
	lunette[] = {
		{
		"G_Diving","NVGoggles","G_Shades_Black","G_Sport_Blackred","G_Tactical_Clear","G_Spectacles","G_Spectacles_Tinted","G_Combat","G_Lowprofile","G_Shades_Red","G_Squares","G_Squares_Tinted","G_Sport_BlackWhite","G_Sport_Blackyellow","G_Tactical_Black"
		},
		{
			0.2,
			0.5,
			0.2,
			0.5,
			0.2,
			0.2,
			0.2,
			0.04,
			0.1,
            0.02,
			0.2,
			0.2,
			0.04,
			0.1,
            0.02
		}
	};
};
